import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { internationalDestinations } from "@/data/international";
import { buildPageMetadata } from "@/lib/seo";

export function generateStaticParams() { return internationalDestinations.map(({ slug }) => ({ slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const destination = internationalDestinations.find((item) => item.slug === slug);
  if (!destination) return {};
  return buildPageMetadata({ title: `${destination.name} | Festival Talent 2027`, description: destination.seoDescription, path: `/destinations/${destination.slug}` });
}

const cardClass = "rounded-3xl border border-yellow-300/15 bg-white/[.04] p-6";

export default async function DestinationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const destination = internationalDestinations.find((item) => item.slug === slug);
  if (!destination) notFound();
  return <main className="min-h-screen bg-black px-6 pb-24 pt-36 text-white sm:px-10 lg:px-20">
    <div className="mx-auto max-w-6xl">
      <Link href="/destinations" className="text-xs font-black uppercase tracking-[.18em] text-yellow-200">← Toutes les destinations</Link>
      <header className="mt-12 max-w-4xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Destination 2027 · {destination.country}</p><h1 className="mt-5 text-5xl font-black uppercase sm:text-7xl">{destination.name}</h1><p className="mt-4 text-xl text-yellow-200">{destination.subtitle}</p><p className="mt-8 text-lg leading-8 text-white/70">{destination.description}</p><p className="mt-5 max-w-3xl text-sm leading-7 text-white/50">Les dates, lieux et formats définitifs seront publiés après confirmation des partenaires et des conditions d’organisation.</p></header>
      <section className="mt-12 grid gap-5 md:grid-cols-3" aria-labelledby="role-title"><div className="md:col-span-2 rounded-3xl border border-yellow-300/25 bg-yellow-300/[.07] p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-200">Rôle dans l’édition</p><h2 id="role-title" className="mt-3 text-2xl font-black">{destination.signature}</h2><p className="mt-3 text-base leading-7 text-white/70">{destination.role}</p></div><div className={cardClass}><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-200">Statut</p><p className="mt-3 text-lg font-black">{destination.statusLabel}</p><p className="mt-3 text-sm leading-6 text-white/50">{destination.status === "Confirmé" ? "Éléments confirmés par l’organisation." : "Programmation, lieux et intervenants à confirmer officiellement."}</p></div></section>
      <section className="mt-16" aria-labelledby="formats-title"><p className="text-xs font-black uppercase tracking-[.25em] text-yellow-300">Pistes éditoriales</p><h2 id="formats-title" className="mt-3 text-3xl font-black uppercase">Formats envisagés</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{destination.formats.map((item) => <div className={cardClass} key={item}><p className="text-sm font-semibold text-white/80">{item}</p><p className="mt-2 text-xs text-white/40">En préparation</p></div>)}</div></section>
      <section className="mt-16 grid gap-5 lg:grid-cols-3"><div className={cardClass}><h2 className="text-xl font-black">Disciplines prioritaires</h2><ul className="mt-5 space-y-2 text-sm text-white/65">{destination.priorityDisciplines.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className={cardClass}><h2 className="text-xl font-black">Publics concernés</h2><ul className="mt-5 space-y-2 text-sm text-white/65">{destination.audiences.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className={cardClass}><h2 className="text-xl font-black">Opportunités recherchées</h2><ul className="mt-5 space-y-2 text-sm text-white/65">{destination.opportunities.map((item) => <li key={item}>• {item}</li>)}</ul></div></section>
      <section className="mt-16" aria-labelledby="prep-title"><p className="text-xs font-black uppercase tracking-[.25em] text-yellow-300">Transparence</p><h2 id="prep-title" className="mt-3 text-3xl font-black uppercase">Ce qui se prépare</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><div className={cardClass}><h3 className="text-lg font-black text-yellow-200">En cours</h3><ul className="mt-4 space-y-2 text-sm leading-6 text-white/65">{destination.preparation.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className={cardClass}><h3 className="text-lg font-black text-yellow-200">À confirmer</h3><ul className="mt-4 space-y-2 text-sm leading-6 text-white/65">{destination.toConfirm.map((item) => <li key={item}>• {item}</li>)}</ul></div></div></section>
      <section className="mt-16" aria-labelledby="timeline-title"><h2 id="timeline-title" className="text-3xl font-black uppercase">Préparation de l’étape</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{destination.timeline.map((item, index) => <div className={`${cardClass} ${item.status === "En cours" ? "border-yellow-300/40" : ""}`} key={item.label}><span className="text-2xl font-black text-yellow-300/60">0{index + 1}</span><p className="mt-4 text-sm font-black">{item.label}</p><p className="mt-2 text-xs text-yellow-200">{item.status}</p></div>)}</div></section>
      <section className="mt-16 rounded-3xl border border-yellow-300/25 bg-gradient-to-br from-yellow-300/[.12] to-white/[.03] p-7 sm:p-10" aria-labelledby="collab-title"><p className="text-xs font-black uppercase tracking-[.25em] text-yellow-300">Partenaires et collaborateurs</p><h2 id="collab-title" className="mt-3 text-3xl font-black uppercase">Participer à la construction de l’étape</h2><p className="mt-4 max-w-3xl text-base leading-7 text-white/65">Festival Talent recherche des partenaires, lieux, médias, structures culturelles et professionnels souhaitant contribuer à la construction de l’étape.</p><div className="mt-5 flex flex-wrap gap-2">{destination.collaborationAudience.map((item) => <span key={item} className="rounded-full border border-white/15 px-3 py-2 text-xs text-white/65">{item}</span>)}</div><p className="mt-7 text-sm leading-6 text-white/50">Les personnes et structures intéressées peuvent manifester leur intérêt avant l’annonce de la programmation définitive. Une manifestation d’intérêt ne constitue ni une confirmation de participation ni un engagement contractuel.</p><Link href="/contact" className="mt-7 inline-flex rounded-full bg-yellow-300 px-5 py-3 text-xs font-black uppercase tracking-[.15em] text-black">Proposer une collaboration</Link></section>
      <nav className="mt-12 flex flex-wrap gap-3" aria-label="Naviguer entre les destinations">{internationalDestinations.map((item) => <Link key={item.slug} aria-current={item.slug === destination.slug ? "page" : undefined} href={`/destinations/${item.slug}`} className={`rounded-full border px-4 py-3 text-xs font-black uppercase tracking-[.14em] ${item.slug === destination.slug ? "border-yellow-300 bg-yellow-300 text-black" : "border-white/15 text-white/75"}`}>{item.name}</Link>)}<Link href="/edition-2027" className="rounded-full border border-white/15 px-4 py-3 text-xs font-black uppercase tracking-[.14em] text-white/75">Édition 2027</Link></nav>
    </div>
  </main>;
}
