"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Compass, Radio, ScanSearch, Sparkles } from "lucide-react";
import { internationalDestinations, internationalDisciplines, internationalProgramme, talentJourney } from "@/data/international";

export function ManifestoSection() {
  const pillars = [{ title: "Détecter", text: "Identifier les nouveaux talents.", icon: ScanSearch }, { title: "Connecter", text: "Créer des rencontres et des opportunités.", icon: Radio }, { title: "Propulser", text: "Offrir une visibilité nationale et internationale.", icon: Sparkles }];
  return <section className="bg-black px-6 py-24 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Le manifeste</p><h2 className="mt-4 max-w-4xl text-3xl font-black uppercase leading-tight sm:text-5xl">Une génération de talents. Plusieurs territoires. Une même scène.</h2><p className="mt-7 max-w-3xl text-base leading-8 text-white/65">Festival Talent crée des ponts entre les talents émergents, les professionnels, les institutions, les marques et les communautés internationales.</p><p className="mt-4 max-w-3xl text-base leading-8 text-white/65">Chaque édition explore de nouveaux pays et imagine des rencontres entre disciplines, cultures et marchés. L&apos;objectif est de détecter, accompagner, connecter et révéler celles et ceux qui façonnent la création de demain.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{pillars.map(({ title, text, icon: Icon }) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><Icon className="text-yellow-300" size={28} /><h3 className="mt-6 text-xl font-black uppercase">{title}</h3><p className="mt-3 text-sm text-white/60">{text}</p></article>)}</div></div></section>;
}

export function DestinationsSection() { return <section className="bg-[#080707] px-6 py-24 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Territoires</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-6xl">Une édition. Trois destinations.</h2></div><Link href="/destinations" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-yellow-200">Voir les destinations <ArrowRight size={15} /></Link></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{internationalDestinations.map((destination, index) => <article key={destination.slug} className="relative overflow-hidden rounded-[2rem] border border-yellow-300/20 bg-gradient-to-b from-white/[.08] to-white/[.02] p-7"><span className="text-6xl font-black text-yellow-300/20">0{index + 1}</span><h3 className="mt-8 text-3xl font-black uppercase">{destination.name}</h3><p className="mt-2 text-sm font-black uppercase tracking-[.14em] text-yellow-300">{destination.signature}</p><p className="mt-5 text-sm leading-7 text-white/60">{destination.role}</p><div className="mt-7 flex flex-wrap gap-4"><span className="inline-flex rounded-full border border-yellow-300/25 bg-yellow-300/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.16em] text-yellow-200">{destination.statusLabel}</span><Link href={`/international-interest?destination=${destination.slug}`} className="inline-flex items-center text-[10px] font-black uppercase tracking-[.16em] text-yellow-200 underline underline-offset-4">Manifester son intérêt</Link></div></article>)}</div></div></section>; }

export function DisciplinesSection() { return <section className="bg-black px-6 py-24 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Les grands univers</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-6xl">Une scène pour chaque langage.</h2><div className="mt-10 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{internationalDisciplines.map((discipline, index) => <article key={discipline} className="min-h-40 rounded-3xl border border-white/10 bg-white/[.04] p-6"><span className="text-xs font-black text-yellow-300">0{index + 1}</span><h3 className="mt-10 text-lg font-black uppercase leading-tight">{discipline}</h3></article>)}</div></div></section>; }

export function TalentJourneySection() { return <section className="bg-[#080707] px-6 py-24 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Le parcours d&apos;un talent</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-6xl">De la candidature à la scène internationale.</h2><p className="mt-6 text-base leading-8 text-white/65">De la candidature à la scène internationale, Festival Talent construit un parcours progressif destiné à identifier, préparer et valoriser les talents.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{talentJourney.map((step, index) => <div key={step} className="rounded-3xl border border-yellow-300/20 bg-yellow-300/[.06] p-5"><span className="text-3xl font-black text-yellow-300/50">0{index + 1}</span><p className="mt-8 text-sm font-black uppercase">{step}</p></div>)}</div><p className="mt-8 text-xs leading-6 text-white/45">Les opportunités proposées dépendent des disciplines, des formats, des critères de sélection et des programmes confirmés. Une inscription ne garantit pas automatiquement une participation aux étapes internationales.</p></div></section>; }

export function InternationalProgrammeSection() {
  const [activeDestination, setActiveDestination] = useState(internationalProgramme[0].destination);
  const active = internationalProgramme.find((item) => item.destination === activeDestination) ?? internationalProgramme[0];
  return <section className="bg-black px-6 py-24 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Programme international</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-6xl">Un programme en mouvement.</h2><div className="mt-10 flex flex-wrap gap-2" role="tablist" aria-label="Choisir une destination"><button type="button" role="tab" aria-selected={activeDestination === "Sénégal"} onClick={() => setActiveDestination("Sénégal")} className={`rounded-full px-5 py-3 text-xs font-black uppercase tracking-[.16em] ${activeDestination === "Sénégal" ? "bg-yellow-300 text-black" : "border border-white/15 text-white/70"}`}>Sénégal</button><button type="button" role="tab" aria-selected={activeDestination === "Paris"} onClick={() => setActiveDestination("Paris")} className={`rounded-full px-5 py-3 text-xs font-black uppercase tracking-[.16em] ${activeDestination === "Paris" ? "bg-yellow-300 text-black" : "border border-white/15 text-white/70"}`}>Paris</button><button type="button" role="tab" aria-selected={activeDestination === "Rome"} onClick={() => setActiveDestination("Rome")} className={`rounded-full px-5 py-3 text-xs font-black uppercase tracking-[.16em] ${activeDestination === "Rome" ? "bg-yellow-300 text-black" : "border border-white/15 text-white/70"}`}>Rome</button></div><article className="mt-6 rounded-3xl border border-yellow-300/20 bg-white/[.04] p-7" role="tabpanel"><Compass className="text-yellow-300" size={26} /><h3 className="mt-6 text-2xl font-black uppercase">{active.destination}</h3><p className="mt-3 text-sm leading-7 text-white/60">{active.phase}</p><span className="mt-7 inline-flex text-[10px] font-black uppercase tracking-[.16em] text-white/45">Événement en préparation · Date prochainement annoncée</span></article></div></section>;
}
