import type { Metadata } from "next";
import Link from "next/link";
import InternationalHeroSection from "@/components/home/InternationalHeroSection";
import { DestinationsSection, DisciplinesSection, InternationalProgrammeSection, ManifestoSection, TalentJourneySection } from "@/components/home/InternationalSections";
import { buildPageMetadata } from "@/lib/seo";

export const metadata: Metadata = buildPageMetadata({ title: "Édition 2027 | Sénégal, Paris et Rome", description: "La vision internationale de Festival Talent 2027, entre le Sénégal, Paris et Rome, avec des étapes dont la programmation est confirmée progressivement.", path: "/edition-2027" });

export default function Edition2027Page() { return <main className="min-h-screen bg-black"><InternationalHeroSection /><ManifestoSection /><section className="bg-[#080707] px-6 py-16 text-white sm:px-10 lg:px-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.3em] text-yellow-300">Rôles complémentaires</p><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-black">Sénégal</h2><p className="mt-3 text-sm text-white/60">Détecter et révéler.</p><Link href="/international-interest?destination=senegal" className="mt-5 inline-flex text-xs font-black uppercase tracking-[.12em] text-yellow-200 underline">Manifester son intérêt</Link></article><article className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-black">Paris</h2><p className="mt-3 text-sm text-white/60">Connecter et rendre visible.</p><Link href="/international-interest?destination=paris" className="mt-5 inline-flex text-xs font-black uppercase tracking-[.12em] text-yellow-200 underline">Manifester son intérêt</Link></article><article className="rounded-3xl border border-white/10 p-6"><h2 className="text-xl font-black">Rome</h2><p className="mt-3 text-sm text-white/60">Créer et dialoguer.</p><Link href="/international-interest?destination=rome" className="mt-5 inline-flex text-xs font-black uppercase tracking-[.12em] text-yellow-200 underline">Manifester son intérêt</Link></article></div><p className="mt-8 text-sm leading-7 text-white/45">Les étapes internationales encore en préparation seront annoncées après validation officielle des formats, lieux et partenaires.</p></div></section><DestinationsSection /><DisciplinesSection /><TalentJourneySection /><InternationalProgrammeSection /></main>; }
